defaults:
  - _self_
  - user: ${oc.env:USER}
  - model@sample_model: gpt
  - model@probs_model: vllm
  - eval: clinicaltrial
  - source@reddit: reddit
  - source@pubmed: pubmed
  - estimator: natural_ipw


seed: 10
train_ratio: 0.6
condition: diabetes
experiment_name: test
save_path: ${user.save_path}/naturalv2/results
data_path: ${user.data_path}/naturalv2
date_time: ${now:%Y-%m-%d}_${now:%H-%M-%S}
load_model: True

filter_by_date: False
