_target_: naturalv2.models.claude.Claude
model_name: claude-3-5-sonnet-20241022
anthropic_api_key_path: /h/290/nikita/anthropic_api_key.txt   
temperature: 0.7
top_p: 1
max_tokens: 512
seed: ${..seed}